//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomoticProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceTopic
    {
        public int DeviceTopicID { get; set; }
        public int DeviceID { get; set; }
        public int TopicID { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
