//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomoticProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceState
    {
        public int DeviceStateId { get; set; }
        public int DeviceId { get; set; }
        public int StateId { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual State State { get; set; }
    }
}
