//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomoticProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceOnTime
    {
        public int DeviceOnTimeID { get; set; }
        public int RoomID { get; set; }
        public int DeviceID { get; set; }
        public System.DateTime OnTime { get; set; }
        public Nullable<System.DateTime> OffTime { get; set; }
        public Nullable<decimal> OnTimeDuration { get; set; }
        public Nullable<int> OnUserID { get; set; }
        public Nullable<int> OffUserID { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Room Room { get; set; }
    }
}
