//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomoticProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomDevice
    {
        public int RoomDeviceID { get; set; }
        public int RoomID { get; set; }
        public int DeviceID { get; set; }
        public int StateID { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<System.DateTime> OnTime { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Room Room { get; set; }
    }
}
